baseURL = "https://USERNAME.github.io/"
languageCode = "en-us"
title = "Kaitao Song"
theme = "PaperMod"

[pagination]
pagerSize = 5

[params]
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowShareButtons = false
  ShowCodeCopyButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true

[params.profileMode]
  enabled = true
  title = "Kaitao Song"
  subtitle = "Research Scientist | Large Language Models | AI Agents | NLP"
  imageUrl = "icon.png"
  imageWidth = 160
  imageHeight = 160

  [[params.profileMode.buttons]]
    name = "Publications"
    url = "/publications/"

  [[params.profileMode.buttons]]
    name = "Projects"
    url = "/projects/"

  [[params.profileMode.buttons]]
    name = "About Me"
    url = "/about/"

[[params.socialIcons]]
  name = "github"
  url = "https://github.com/stillkeeptry"

[[params.socialIcons]]
  name = "googlescholar"
  url = "https://scholar.google.com.hk/citations?user=LLk9dR8AAAAJ"

[[params.socialIcons]]
  name = "x"
  url = "https://x.com/SongKaitao"

[[params.socialIcons]]
  name = "linkedin"
  url = "https://www.linkedin.com/in/kaitao-song-720147b7/"

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About Me"
    url = "/about/"
    weight = 5

  [[menu.main]]
    identifier = "publications"
    name = "Publications"
    url = "/publications/"
    weight = 10

  [[menu.main]]
    identifier = "projects"
    name = "Projects"
    url = "/projects/"
    weight = 20
